module.exports = {
  apps: [
    {
      name: "schedowl-app",
      script: "pnpm",
      args: "start",
      env: {
        NODE_ENV: "production",
        PORT: 3000,
      },
      instances: 1,
      exec_mode: "fork",
      watch: false,
      max_memory_restart: "1G",
      kill_timeout: 5000,
      listen_timeout: 10000,
      exp_backoff_restart_delay: 100,
      autorestart: true,
      force: false,
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      min_uptime: "60s",
      max_restarts: 5,
      restart_delay: 4000,
      error_file: "/root/.pm2/logs/schedowl-app-error.log",
      out_file: "/root/.pm2/logs/schedowl-app-out.log",
      time: true,
      wait_ready: true,
      shutdown_with_message: true,
      increment_var: "PORT",
    },
    {
      name: "schedowl-worker",
      script: "pnpm",
      args: "worker",
      env: {
        NODE_ENV: "production",
      },
      instances: 1,
      exec_mode: "fork",
      watch: false,
      max_memory_restart: "1G",
      kill_timeout: 10000,
      listen_timeout: 10000,
      exp_backoff_restart_delay: 100,
      autorestart: true,
      force: false,
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      min_uptime: "60s",
      max_restarts: 5,
      restart_delay: 4000,
      error_file: "/root/.pm2/logs/schedowl-worker-error.log",
      out_file: "/root/.pm2/logs/schedowl-worker-out.log",
      time: true,
      wait_ready: true,
      shutdown_with_message: true,
    },
  ],
};
