export const MONTHLY_SUBSCRIPTION_PLANS = [
  {
    id: "pdt_gKr5msrwwpD3qzsEsa2Pd",
    title: "Basic (Monthly)",
    price: 15.0,
    popular: false,
    image: {
      src: "https://prod-dodo-backend-live-mode.s3.ap-south-1.amazonaws.com/businesses/bus_ceLckD961daGStI1QEHBQ/products/pdt_gKr5msrwwpD3qzsEsa2Pd/94ef6fe2-c8c0-4a73-a60f-205fda6d78e4",
    },
    features: [
      { name: "Scheduler", available: true },
      {
        name: "Text Editor (Bold, Italics, Bullets)",
        available: true,
      },
      { name: "Basic Analytics", available: true },
      { name: "Write & Preview Posts", available: true },
      { name: "Organize Your Drafts", available: true },
      { name: "Manage Multiple Accounts / Workspaces", available: false },
      { name: "Multiple Contributors/Managers", available: false },
      { name: "AI-Powered Advanced Analytics", available: false },
      { name: "AI Chat Assistant for Content Ideation", available: false },
      { name: "Generate Posts Using SchedOwl AI", available: false },
      { name: "Mimic Brand Voice Across Clients", available: false },
    ],
    interval: "monthly",
    intervalCount: 1,
    trialDays: 0,
  },
  {
    id: "pdt_3TTCaKqK0CITToeAgNbJO",
    title: "Pro (Monthly)",
    price: 49.0,
    popular: true,
    image: {
      src: "https://prod-dodo-backend-live-mode.s3.ap-south-1.amazonaws.com/businesses/bus_ceLckD961daGStI1QEHBQ/products/pdt_gKr5msrwwpD3qzsEsa2Pd/94ef6fe2-c8c0-4a73-a60f-205fda6d78e4",
    },
    features: [
      { name: "Scheduler", available: true },
      {
        name: "Text Editor (Bold, Italics, Bullets)",
        available: true,
      },
      { name: "Basic Analytics", available: true },
      { name: "Write & Preview Posts", available: true },
      { name: "Organize Your Drafts", available: true },
      { name: "Manage Multiple Accounts / Workspaces", available: true },
      { name: "Multiple Contributors/Managers", available: true },
      { name: "AI-Powered Advanced Analytics", available: true },
      { name: "AI Chat Assistant for Content Ideation", available: true },
      { name: "Generate Posts Using SchedOwl AI", available: true },
      { name: "Mimic Brand Voice Across Clients", available: true },
    ],
    interval: "monthly",
    intervalCount: 1,
    trialDays: 0,
  },
  {
    id: "pdt_j6DQCyzn8A0118a63qnJt",
    title: "Super (Monthly)",
    price: 79.0,
    popular: false,
    image: {
      src: "https://prod-dodo-backend-live-mode.s3.ap-south-1.amazonaws.com/businesses/bus_ceLckD961daGStI1QEHBQ/products/pdt_gKr5msrwwpD3qzsEsa2Pd/94ef6fe2-c8c0-4a73-a60f-205fda6d78e4",
    },
    features: [
      { name: "Scheduler", available: true },
      {
        name: "Text Editor (Bold, Italics, Bullets)",
        available: true,
      },
      { name: "Basic Analytics", available: true },
      { name: "Write & Preview Posts", available: true },
      { name: "Organize Your Drafts", available: true },
      { name: "Manage Multiple Accounts / Workspaces", available: true },
      { name: "Multiple Contributors/Managers", available: true },
      { name: "AI-Powered Advanced Analytics", available: true },
      { name: "AI Chat Assistant for Content Ideation", available: true },
      { name: "Generate Posts Using SchedOwl AI", available: true },
      { name: "Mimic Brand Voice Across Clients", available: true },
    ],
    interval: "monthly",
    intervalCount: 1,
    trialDays: 0,
  },
];

export const YEARLY_SUBSCRIPTION_PLANS = [
  {
    id: "pdt_WImcYTSJYqzRmu1VM1Pnp",
    title: "Basic (Yearly)",
    price: 150.0,
    popular: false,
    image: {
      src: "https://prod-dodo-backend-live-mode.s3.ap-south-1.amazonaws.com/businesses/bus_ceLckD961daGStI1QEHBQ/products/pdt_gKr5msrwwpD3qzsEsa2Pd/94ef6fe2-c8c0-4a73-a60f-205fda6d78e4",
    },
    features: [
      { name: "Scheduler", available: true },
      {
        name: "Text Editor (Bold, Italics, Bullets)",
        available: true,
      },
      { name: "Basic Analytics", available: true },
      { name: "Write & Preview Posts", available: true },
      { name: "Organize Your Drafts", available: true },
      { name: "Manage Multiple Accounts / Workspaces", available: false },
      { name: "Multiple Contributors/Managers", available: false },
      { name: "AI-Powered Advanced Analytics", available: false },
      { name: "AI Chat Assistant for Content Ideation", available: false },
      { name: "Generate Posts Using SchedOwl AI", available: false },
      { name: "Mimic Brand Voice Across Clients", available: false },
    ],
    interval: "yearly",
    intervalCount: 1,
    trialDays: 0,
  },
  {
    id: "pdt_TlcLgUlNjtlvyiYlJu5qP",
    title: "Pro (Yearly)",
    price: 490.0,
    popular: true,
    image: {
      src: "https://prod-dodo-backend-live-mode.s3.ap-south-1.amazonaws.com/businesses/bus_ceLckD961daGStI1QEHBQ/products/pdt_gKr5msrwwpD3qzsEsa2Pd/94ef6fe2-c8c0-4a73-a60f-205fda6d78e4",
    },
    features: [
      { name: "Scheduler", available: true },
      {
        name: "Text Editor (Bold, Italics, Bullets)",
        available: true,
      },
      { name: "Basic Analytics", available: true },
      { name: "Write & Preview Posts", available: true },
      { name: "Organize Your Drafts", available: true },
      { name: "Manage Multiple Accounts / Workspaces", available: true },
      { name: "Multiple Contributors/Managers", available: true },
      { name: "AI-Powered Advanced Analytics", available: true },
      { name: "AI Chat Assistant for Content Ideation", available: true },
      { name: "Generate Posts Using SchedOwl AI", available: true },
      { name: "Mimic Brand Voice Across Clients", available: true },
    ],
    interval: "yearly",
    intervalCount: 1,
    trialDays: 0,
  },
  {
    id: "pdt_MJLYrI9KY3XkrS0NKpr03",
    title: "Super (Yearly)",
    price: 790.0,
    popular: false,
    image: {
      src: "https://prod-dodo-backend-live-mode.s3.ap-south-1.amazonaws.com/businesses/bus_ceLckD961daGStI1QEHBQ/products/pdt_gKr5msrwwpD3qzsEsa2Pd/94ef6fe2-c8c0-4a73-a60f-205fda6d78e4",
    },
    features: [
      { name: "Scheduler", available: true },
      {
        name: "Text Editor (Bold, Italics, Bullets)",
        available: true,
      },
      { name: "Basic Analytics", available: true },
      { name: "Write & Preview Posts", available: true },
      { name: "Organize Your Drafts", available: true },
      { name: "Manage Multiple Accounts / Workspaces", available: true },
      { name: "Multiple Contributors/Managers", available: true },
      { name: "AI-Powered Advanced Analytics", available: true },
      { name: "AI Chat Assistant for Content Ideation", available: true },
      { name: "Generate Posts Using SchedOwl AI", available: true },
      { name: "Mimic Brand Voice Across Clients", available: true },
    ],
    interval: "yearly",
    intervalCount: 1,
    trialDays: 0,
  },
];
