export const MONTHLY_SUBSCRIPTION_PLANS = [
  {
    id: "pdt_QsOa1DXWzX7j1gpoFqeCV",
    title: "Basic",
    price: 19.0,
    popular: false,
    image: {
      src: "https://prod-dodo-backend-test-mode.s3.ap-south-1.amazonaws.com/businesses/bus_UBFQWMwUOlJd86nDAjsfl/products/pdt_QsOa1DXWzX7j1gpoFqeCV/8a8510c5-9733-4f5f-93bf-124d1a526d86",
    },
    features: [
      { name: "Scheduler", available: true },
      {
        name: "Text Editor (Bold, Italics, Bullets)",
        available: true,
      },
      { name: "Basic Analytics", available: true },
      { name: "Write & Preview Posts", available: true },
      { name: "Organize Your Drafts", available: true },
      { name: "Manage Multiple Accounts / Workspaces", available: false },
      { name: "Multiple Contributors/Managers", available: false },
      { name: "AI-Powered Advanced Analytics", available: false },
      { name: "AI Chat Assistant for Content Ideation", available: false },
      { name: "Generate Posts Using SchedOwl AI", available: false },
      { name: "Mimic Brand Voice Across Clients", available: false },
    ],
    interval: "monthly",
    intervalCount: 1,
    trialDays: 0,
  },
  {
    id: "pdt_E9pl7XcBTqmmKrjvCFsWP",
    title: "Pro",
    price: 49.0,
    popular: true,
    image: {
      src: "https://prod-dodo-backend-test-mode.s3.ap-south-1.amazonaws.com/businesses/bus_UBFQWMwUOlJd86nDAjsfl/products/pdt_OLP93DRSm87erHfuev0iF/790cc780-200d-4f00-9180-cf56eb8c58ca",
    },
    features: [
      { name: "Scheduler", available: true },
      {
        name: "Text Editor (Bold, Italics, Bullets)",
        available: true,
      },
      { name: "Basic Analytics", available: true },
      { name: "Write & Preview Posts", available: true },
      { name: "Organize Your Drafts", available: true },
      { name: "Manage Multiple Accounts / Workspaces", available: true },
      { name: "Multiple Contributors/Managers", available: true },
      { name: "AI-Powered Advanced Analytics", available: true },
      { name: "AI Chat Assistant for Content Ideation", available: true },
      { name: "Generate Posts Using SchedOwl AI", available: true },
      { name: "Mimic Brand Voice Across Clients", available: true },
    ],
    interval: "monthly",
    intervalCount: 1,
    trialDays: 0,
  },
  {
    id: "pdt_1JfkKq48HtY76a0Lya1Jp",
    title: "Super",
    price: 79.0,
    popular: false,
    image: {
      src: "https://prod-dodo-backend-test-mode.s3.ap-south-1.amazonaws.com/businesses/bus_UBFQWMwUOlJd86nDAjsfl/products/pdt_Pu9Kndq1ieERSHHG5yZY4/2749c892-ba87-4a73-8f48-3b7622f758c4",
    },
    features: [
      { name: "Scheduler", available: true },
      {
        name: "Text Editor (Bold, Italics, Bullets)",
        available: true,
      },
      { name: "Basic Analytics", available: true },
      { name: "Write & Preview Posts", available: true },
      { name: "Organize Your Drafts", available: true },
      { name: "Manage Multiple Accounts / Workspaces", available: true },
      { name: "Multiple Contributors/Managers", available: true },
      { name: "AI-Powered Advanced Analytics", available: true },
      { name: "AI Chat Assistant for Content Ideation", available: true },
      { name: "Generate Posts Using SchedOwl AI", available: true },
      { name: "Mimic Brand Voice Across Clients", available: true },
    ],
    interval: "monthly",
    intervalCount: 1,
    trialDays: 0,
  },
];

export const YEARLY_SUBSCRIPTION_PLANS = [
  {
    id: "pdt_RHVD3hhaZTSx37dYxqMS2",
    title: "Basic",
    price: 190.0,
    popular: false,
    image: {
      src: "https://prod-dodo-backend-test-mode.s3.ap-south-1.amazonaws.com/businesses/bus_UBFQWMwUOlJd86nDAjsfl/products/pdt_QsOa1DXWzX7j1gpoFqeCV/8a8510c5-9733-4f5f-93bf-124d1a526d86",
    },
    features: [
      { name: "Scheduler", available: true },
      {
        name: "Text Editor (Bold, Italics, Bullets)",
        available: true,
      },
      { name: "Basic Analytics", available: true },
      { name: "Write & Preview Posts", available: true },
      { name: "Organize Your Drafts", available: true },
      { name: "Manage Multiple Accounts / Workspaces", available: false },
      { name: "Multiple Contributors/Managers", available: false },
      { name: "AI-Powered Advanced Analytics", available: false },
      { name: "AI Chat Assistant for Content Ideation", available: false },
      { name: "Generate Posts Using SchedOwl AI", available: false },
      { name: "Mimic Brand Voice Across Clients", available: false },
    ],
    interval: "yearly",
    intervalCount: 1,
    trialDays: 0,
  },
  {
    id: "pdt_OLP93DRSm87erHfuev0iF",
    title: "Pro",
    price: 490.0,
    popular: true,
    image: {
      src: "https://prod-dodo-backend-test-mode.s3.ap-south-1.amazonaws.com/businesses/bus_UBFQWMwUOlJd86nDAjsfl/products/pdt_OLP93DRSm87erHfuev0iF/790cc780-200d-4f00-9180-cf56eb8c58ca",
    },
    features: [
      { name: "Scheduler", available: true },
      {
        name: "Text Editor (Bold, Italics, Bullets)",
        available: true,
      },
      { name: "Basic Analytics", available: true },
      { name: "Write & Preview Posts", available: true },
      { name: "Organize Your Drafts", available: true },
      { name: "Manage Multiple Accounts / Workspaces", available: true },
      { name: "Multiple Contributors/Managers", available: true },
      { name: "AI-Powered Advanced Analytics", available: true },
      { name: "AI Chat Assistant for Content Ideation", available: true },
      { name: "Generate Posts Using SchedOwl AI", available: true },
      { name: "Mimic Brand Voice Across Clients", available: true },
    ],
    interval: "yearly",
    intervalCount: 1,
    trialDays: 0,
  },
  {
    id: "pdt_Pu9Kndq1ieERSHHG5yZY4",
    title: "Super",
    price: 790.0,
    popular: false,
    image: {
      src: "https://prod-dodo-backend-test-mode.s3.ap-south-1.amazonaws.com/businesses/bus_UBFQWMwUOlJd86nDAjsfl/products/pdt_Pu9Kndq1ieERSHHG5yZY4/2749c892-ba87-4a73-8f48-3b7622f758c4",
    },
    features: [
      { name: "Scheduler", available: true },
      {
        name: "Text Editor (Bold, Italics, Bullets)",
        available: true,
      },
      { name: "Basic Analytics", available: true },
      { name: "Write & Preview Posts", available: true },
      { name: "Organize Your Drafts", available: true },
      { name: "Manage Multiple Accounts / Workspaces", available: true },
      { name: "Multiple Contributors/Managers", available: true },
      { name: "AI-Powered Advanced Analytics", available: true },
      { name: "AI Chat Assistant for Content Ideation", available: true },
      { name: "Generate Posts Using SchedOwl AI", available: true },
      { name: "Mimic Brand Voice Across Clients", available: true },
    ],
    interval: "yearly",
    intervalCount: 1,
    trialDays: 0,
  },
];
