export const MONTHLY_SUBSCRIPTION_PLANS = [
  {
    id: "pdt_xnnN4OqShvoUqbALQ2w3h",
    title: "Basic (Monthly)",
    price: 19.0,
    popular: false,
    image: {
      src: "https://prod-dodo-backend-test-mode.s3.ap-south-1.amazonaws.com/businesses/bus_ceLckD961daGStI1QEHBQ/products/pdt_xnnN4OqShvoUqbALQ2w3h/638539c3-a442-42b5-a44e-23dfa6cae57d",
    },
    features: [
      { name: "Scheduler", available: true },
      {
        name: "Text Editor (Bold, Italics, Bullets)",
        available: true,
      },
      { name: "Basic Analytics", available: true },
      { name: "Write & Preview Posts", available: true },
      { name: "Organize Your Drafts", available: true },
      { name: "Manage Multiple Accounts / Workspaces", available: false },
      { name: "Multiple Contributors/Managers", available: false },
      { name: "AI-Powered Advanced Analytics", available: false },
      { name: "AI Chat Assistant for Content Ideation", available: false },
      { name: "Generate Posts Using SchedOwl AI", available: false },
      { name: "Mimic Brand Voice Across Clients", available: false },
    ],
    interval: "monthly",
    intervalCount: 1,
    trialDays: 0,
  },
  {
    id: "pdt_IMmzmIxIZjfBynfDofZsW",
    title: "Pro (Monthly)",
    price: 49.0,
    popular: true,
    image: {
      src: "https://prod-dodo-backend-test-mode.s3.ap-south-1.amazonaws.com/businesses/bus_ceLckD961daGStI1QEHBQ/products/pdt_xnnN4OqShvoUqbALQ2w3h/638539c3-a442-42b5-a44e-23dfa6cae57d",
    },
    features: [
      { name: "Scheduler", available: true },
      {
        name: "Text Editor (Bold, Italics, Bullets)",
        available: true,
      },
      { name: "Basic Analytics", available: true },
      { name: "Write & Preview Posts", available: true },
      { name: "Organize Your Drafts", available: true },
      { name: "Manage Multiple Accounts / Workspaces", available: true },
      { name: "Multiple Contributors/Managers", available: true },
      { name: "AI-Powered Advanced Analytics", available: true },
      { name: "AI Chat Assistant for Content Ideation", available: true },
      { name: "Generate Posts Using SchedOwl AI", available: true },
      { name: "Mimic Brand Voice Across Clients", available: true },
    ],
    interval: "monthly",
    intervalCount: 1,
    trialDays: 0,
  },
  {
    id: "pdt_WTtT3nff6Rg7J7k3AZLNr",
    title: "Super (Monthly)",
    price: 79.0,
    popular: false,
    image: {
      src: "https://prod-dodo-backend-test-mode.s3.ap-south-1.amazonaws.com/businesses/bus_ceLckD961daGStI1QEHBQ/products/pdt_xnnN4OqShvoUqbALQ2w3h/638539c3-a442-42b5-a44e-23dfa6cae57d",
    },
    features: [
      { name: "Scheduler", available: true },
      {
        name: "Text Editor (Bold, Italics, Bullets)",
        available: true,
      },
      { name: "Basic Analytics", available: true },
      { name: "Write & Preview Posts", available: true },
      { name: "Organize Your Drafts", available: true },
      { name: "Manage Multiple Accounts / Workspaces", available: true },
      { name: "Multiple Contributors/Managers", available: true },
      { name: "AI-Powered Advanced Analytics", available: true },
      { name: "AI Chat Assistant for Content Ideation", available: true },
      { name: "Generate Posts Using SchedOwl AI", available: true },
      { name: "Mimic Brand Voice Across Clients", available: true },
    ],
    interval: "monthly",
    intervalCount: 1,
    trialDays: 0,
  },
];

export const YEARLY_SUBSCRIPTION_PLANS = [
  {
    id: "pdt_KXl5n920EJTY0dKUFZs8S",
    title: "Basic (Yearly)",
    price: 190.0,
    popular: false,
    image: {
      src: "https://prod-dodo-backend-test-mode.s3.ap-south-1.amazonaws.com/businesses/bus_ceLckD961daGStI1QEHBQ/products/pdt_xnnN4OqShvoUqbALQ2w3h/638539c3-a442-42b5-a44e-23dfa6cae57d",
    },
    features: [
      { name: "Scheduler", available: true },
      {
        name: "Text Editor (Bold, Italics, Bullets)",
        available: true,
      },
      { name: "Basic Analytics", available: true },
      { name: "Write & Preview Posts", available: true },
      { name: "Organize Your Drafts", available: true },
      { name: "Manage Multiple Accounts / Workspaces", available: false },
      { name: "Multiple Contributors/Managers", available: false },
      { name: "AI-Powered Advanced Analytics", available: false },
      { name: "AI Chat Assistant for Content Ideation", available: false },
      { name: "Generate Posts Using SchedOwl AI", available: false },
      { name: "Mimic Brand Voice Across Clients", available: false },
    ],
    interval: "yearly",
    intervalCount: 1,
    trialDays: 0,
  },
  {
    id: "pdt_rp0qQXyldU6PAwYofF6Kc",
    title: "Pro (Yearly)",
    price: 490.0,
    popular: true,
    image: {
      src: "https://prod-dodo-backend-test-mode.s3.ap-south-1.amazonaws.com/businesses/bus_ceLckD961daGStI1QEHBQ/products/pdt_xnnN4OqShvoUqbALQ2w3h/638539c3-a442-42b5-a44e-23dfa6cae57d",
    },
    features: [
      { name: "Scheduler", available: true },
      {
        name: "Text Editor (Bold, Italics, Bullets)",
        available: true,
      },
      { name: "Basic Analytics", available: true },
      { name: "Write & Preview Posts", available: true },
      { name: "Organize Your Drafts", available: true },
      { name: "Manage Multiple Accounts / Workspaces", available: true },
      { name: "Multiple Contributors/Managers", available: true },
      { name: "AI-Powered Advanced Analytics", available: true },
      { name: "AI Chat Assistant for Content Ideation", available: true },
      { name: "Generate Posts Using SchedOwl AI", available: true },
      { name: "Mimic Brand Voice Across Clients", available: true },
    ],
    interval: "yearly",
    intervalCount: 1,
    trialDays: 0,
  },
  {
    id: "pdt_SBri6FzWKA4CvUfF8PPsi",
    title: "Super (Yearly)",
    price: 790.0,
    popular: false,
    image: {
      src: "https://prod-dodo-backend-test-mode.s3.ap-south-1.amazonaws.com/businesses/bus_ceLckD961daGStI1QEHBQ/products/pdt_xnnN4OqShvoUqbALQ2w3h/638539c3-a442-42b5-a44e-23dfa6cae57d",
    },
    features: [
      { name: "Scheduler", available: true },
      {
        name: "Text Editor (Bold, Italics, Bullets)",
        available: true,
      },
      { name: "Basic Analytics", available: true },
      { name: "Write & Preview Posts", available: true },
      { name: "Organize Your Drafts", available: true },
      { name: "Manage Multiple Accounts / Workspaces", available: true },
      { name: "Multiple Contributors/Managers", available: true },
      { name: "AI-Powered Advanced Analytics", available: true },
      { name: "AI Chat Assistant for Content Ideation", available: true },
      { name: "Generate Posts Using SchedOwl AI", available: true },
      { name: "Mimic Brand Voice Across Clients", available: true },
    ],
    interval: "yearly",
    intervalCount: 1,
    trialDays: 0,
  },
];
